# Generated by Django 2.1.7 on 2019-03-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbook',
            name='due_date',
            field=models.DateField(),
        ),
    ]
