# Generated by Django 2.1.7 on 2019-03-28 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_auto_20190328_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbook',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentals.Book'),
        ),
        migrations.AlterField(
            model_name='customerbook',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentals.Customer'),
        ),
    ]
